### ISSUE TITLE
java.io.EOFException when running Neo4j using docker

### ISSUE THREAD

**Issue by weifanwu** [Goblin-Ecosystem/Neo4jWeaverDocker#2]
Hi everyone,

After running docker-compose up --build, I'm getting the following error:

"java.io.EOFException"

I did some research, and some posts suggest that it could be caused by low disk space (reference: [StackOverflow](https://stackoverflow.com/questions/40992148/how-low-disk-space-can-cause-java-io-eofexception)). Indeed, both images are quite large (60GB), so I upgraded the disk image. Despite this, I'm still encountering the same error.

Can anyone help me figure out what's going wrong? Apologies if this is a simple issue, but I'd appreciate any guidance.

Thanks!

![image](https://github.com/user-attachments/assets/5b022e6a-93bd-4f67-8485-1640f9de29df)
<img width="1151" alt="image" src="https://github.com/user-attachments/assets/eb7d0340-ce78-4265-9c2e-d7473e1cdf15">

**Comment by weifanwu** [comment]
@DaJaime wonder if you could provide me any insights? thanks!

**Comment by pascalpoizat** [comment]
OK, I was able to reproduce the error. Trying to find a solution.

**Comment by weifanwu** [comment]
> OK, I was able to reproduce the error. Trying to find a solution.

I have install neo4j and weaver without using docker and everything works.

**Comment by holen-zhang** [comment]
Hi, is there any update with this issue? I am trying to run Neo4j on the "with_metrics_goblin_maven_30_08_24.dump" dataset and I got the same error. I manually downloaded the demp and changed the docker file to:
```
FROM neo4j:4.4.36-community

RUN apt-get update && apt-get install -y curl && apt-get clean

COPY with_metrics_goblin_maven_30_08_24.dump /data/Goblin_Maven_Central_Graph.dump

ENV NEO4J_AUTH=neo4j/Password1

RUN neo4j-admin load --from=/data/Goblin_Maven_Central_Graph.dump --database=neo4j --force
```

Then I built the project (https://github.com/Goblin-Ecosystem/Neo4jWeaverDocker/tree/metrics_dataset) by following the instructions.

The console outputs are:
```
goblinWeaver  | Exception in thread "main" java.lang.reflect.InvocationTargetException
goblinWeaver  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
goblinWeaver  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
goblinWeaver  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
goblinWeaver  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
goblinWeaver  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
goblinWeaver  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
goblinWeaver  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
goblinWeaver  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
goblinWeaver  | Caused by: org.neo4j.driver.exceptions.TransientException: Database 'neo4j' is unavailable.
goblinWeaver  | 	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:111)
goblinWeaver  | 	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:64)
goblinWeaver  | 	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:49)
goblinWeaver  | 	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:34)
goblinWeaver  | 	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:49)
goblinWeaver  | 	at com.cifre.sap.su.goblinWeaver.graphDatabase.neo4j.Neo4jGraphDatabase.<init>(Neo4jGraphDatabase.java:38)
goblinWeaver  | 	at com.cifre.sap.su.goblinWeaver.graphDatabase.GraphDatabaseSingleton.getInstance(GraphDatabaseSingleton.java:21)
goblinWeaver  | 	at com.cifre.sap.su.goblinWeaver.Neo4jEcosystemWeaverApplication.main(Neo4jEcosystemWeaverApplication.java:13)
goblinWeaver  | 	... 8 more
goblinWeaver  | 	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
goblinWeaver  | 		at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:87)
goblinWeaver  | 		at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:107)
goblinWeaver  | 		at org.neo4j.driver.internal.messaging.common.CommonMessageReader.unpackFailureMessage(CommonMessageReader.java:75)
goblinWeaver  | 		at org.neo4j.driver.internal.messaging.common.CommonMessageReader.read(CommonMessageReader.java:53)
goblinWeaver  | 		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:81)
goblinWeaver  | 		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:37)
goblinWeaver  | 		at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
goblinWeaver  | 		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
goblinWeaver  | 		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
goblinWeaver  | 		at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:42)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
goblinWeaver  | 		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
goblinWeaver  | 		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
goblinWeaver  | 		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
goblinWeaver  | 		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
goblinWeaver  | 		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
goblinWeaver  | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
goblinWeaver  | 		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
goblinWeaver  | 		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
goblinWeaver  | 		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
goblinWeaver  | 		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
goblinWeaver  | 		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
goblinWeaver  | 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
goblinWeaver  | 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
goblinWeaver  | 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
goblinWeaver  | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
goblinWeaver  | 		at java.base/java.lang.Thread.run(Thread.java:833)
goblinWeaver exited with code 1
```
