### ISSUE TITLE
ERROR StatusLogger Unable to write to stream /logs/debug.log for appender neo4jLog.debug.log

### ISSUE THREAD

**Issue by pascalpoizat** [Goblin-Ecosystem/Neo4jWeaverDocker#3]
Hello

I get this error when launching docker-compose.

```
➜ docker-compose up --build
[+] Building 78.1s (21/21) FINISHED                                                                                              docker:desktop-linux
 => [neo4j internal] load build definition from Dockerfile.neo4j                                                                                 0.0s
 => => transferring dockerfile: 408B                                                                                                             0.0s
 => [neo4j internal] load metadata for docker.io/library/neo4j:4.4.36-community                                                                  1.0s
 => [neo4j auth] library/neo4j:pull token for registry-1.docker.io                                                                               0.0s
 => [neo4j internal] load .dockerignore                                                                                                          0.2s
 => => transferring context: 2B                                                                                                                  0.0s
 => [neo4j 1/4] FROM docker.io/library/neo4j:4.4.36-community@sha256:357deaca05e213b5574b9462def0625b2607ed342a23763ca4dda45b8af70a31            0.0s
 => CACHED [neo4j 2/4] RUN apt-get update && apt-get install -y curl && apt-get clean                                                            0.0s
 => CACHED [neo4j 3/4] RUN curl -C - -L -o /data/Goblin_Maven_Central_Graph.dump https://zenodo.org/records/13683940/files/goblin_maven_30_08_2  0.0s
 => [neo4j 4/4] RUN neo4j-admin load --from=/data/Goblin_Maven_Central_Graph.dump --database=neo4j --force                                      42.7s
 => [neo4j] exporting to image                                                                                                                  33.3s
 => => exporting layers                                                                                                                         33.3s
 => => writing image sha256:489c68b82e503fe2fe491bfc970b1b82c75bc604ccbfff1aea8257717c7ee7c7                                                     0.0s
 => => naming to docker.io/library/neo4jweaverdocker-neo4j                                                                                       0.0s
 => [neo4j] resolving provenance for metadata file                                                                                               0.1s
 => [weaver internal] load build definition from Dockerfile.weaver                                                                               0.0s
 => => transferring dockerfile: 496B                                                                                                             0.0s
 => [weaver internal] load metadata for docker.io/library/openjdk:17-jdk-slim                                                                    0.8s
 => [weaver auth] library/openjdk:pull token for registry-1.docker.io                                                                            0.0s
 => [weaver internal] load .dockerignore                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                  0.0s
 => [weaver 1/5] FROM docker.io/library/openjdk:17-jdk-slim@sha256:aaa3b3cb27e3e520b8f116863d0580c438ed55ecfa0bc126b41f68c3f62f9774              0.0s
 => CACHED [weaver 2/5] RUN apt-get update && apt-get install -y curl && apt-get clean                                                           0.0s
 => CACHED [weaver 3/5] WORKDIR /app                                                                                                             0.0s
 => CACHED [weaver 4/5] RUN curl -C - -L -o /app/goblinWeaver-2.1.0.jar https://github.com/Goblin-Ecosystem/goblinWeaver/releases/download/v2.1  0.0s
 => CACHED [weaver 5/5] RUN chmod -R 777 /app                                                                                                    0.0s
 => [weaver] exporting to image                                                                                                                  0.0s
 => => exporting layers                                                                                                                          0.0s
 => => writing image sha256:d3fb6fa257ed8585c65b29510be5613830d79baf3c425217a5c22f39beb221f5                                                     0.0s
 => => naming to docker.io/library/neo4jweaverdocker-weaver                                                                                      0.0s
 => [weaver] resolving provenance for metadata file                                                                                              0.0s
[+] Running 4/3
 ✔ Network neo4jweaverdocker_default      Created                                                                                                0.0s
 ✔ Volume "neo4jweaverdocker_neo4j-data"  Created                                                                                                0.0s
 ✔ Container neo4jMaven                   Created                                                                                               25.6s
 ✔ Container goblinWeaver                 Created                                                                                                0.0s
Attaching to goblinWeaver, neo4jMaven
neo4jMaven    | Warning: Some files inside "/data" are not writable from inside container. Changing folder owner to neo4j.
neo4jMaven    | 2024-10-10 09:04:43.243+0000 INFO  Starting...
neo4jMaven    | ERROR StatusLogger Unable to write to stream /logs/debug.log for appender neo4jLog.debug.log
neo4jMaven    |  org.neo4j.logging.shaded.log4j.core.appender.AppenderLoggingException: Error writing to stream /logs/debug.log
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:252)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.FileManager.writeToDestination(FileManager.java:277)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.rolling.RollingFileManager.writeToDestination(RollingFileManager.java:275)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:294)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:312)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.DefaultReliabilityStrategy.log(DefaultReliabilityStrategy.java:63)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.Logger.log(Logger.java:161)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2661)
neo4jMaven    | 	at org.neo4j.logging.log4j.Log4jLog.warn(Log4jLog.java:124)
neo4jMaven    | 	at org.neo4j.kernel.info.JvmChecker.checkJvmCompatibilityAndIssueWarning(JvmChecker.java:68)
neo4jMaven    | 	at org.neo4j.graphdb.factory.module.GlobalModule.<init>(GlobalModule.java:203)
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.createGlobalModule(DatabaseManagementServiceFactory.java:272)
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:133)
neo4jMaven    | 	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142)
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95)
neo4jMaven    | 	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:34)
neo4jMaven    | Caused by: java.io.IOException: No space left on device
neo4jMaven    | 	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
neo4jMaven    | 	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:250)
neo4jMaven    | 	... 33 more
neo4jMaven    | ERROR StatusLogger An exception occurred processing Appender neo4jLog.debug.log
neo4jMaven    |  org.neo4j.logging.shaded.log4j.core.appender.AppenderLoggingException: Error writing to stream /logs/debug.log
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:252)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.FileManager.writeToDestination(FileManager.java:277)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.rolling.RollingFileManager.writeToDestination(RollingFileManager.java:275)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:294)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:312)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.DefaultReliabilityStrategy.log(DefaultReliabilityStrategy.java:63)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.Logger.log(Logger.java:161)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2661)
neo4jMaven    | 	at org.neo4j.logging.log4j.Log4jLog.warn(Log4jLog.java:124)
neo4jMaven    | 	at org.neo4j.kernel.info.JvmChecker.checkJvmCompatibilityAndIssueWarning(JvmChecker.java:68)
neo4jMaven    | 	at org.neo4j.graphdb.factory.module.GlobalModule.<init>(GlobalModule.java:203)
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.createGlobalModule(DatabaseManagementServiceFactory.java:272)
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:133)
neo4jMaven    | 	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142)
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95)
neo4jMaven    | 	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:34)
neo4jMaven    | Caused by: java.io.IOException: No space left on device
neo4jMaven    | 	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
neo4jMaven    | 	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:250)
neo4jMaven    | 	... 33 more
neo4jMaven    | ERROR StatusLogger Unable to write to stream /logs/debug.log for appender neo4jLog.debug.log
neo4jMaven    |  org.neo4j.logging.shaded.log4j.core.appender.AppenderLoggingException: Error writing to stream /logs/debug.log
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:252)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.FileManager.writeToDestination(FileManager.java:277)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.rolling.RollingFileManager.writeToDestination(RollingFileManager.java:275)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:294)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:312)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.DefaultReliabilityStrategy.log(DefaultReliabilityStrategy.java:63)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.Logger.log(Logger.java:161)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2661)
neo4jMaven    | 	at org.neo4j.logging.log4j.Log4jLog.warn(Log4jLog.java:124)
neo4jMaven    | 	at org.neo4j.kernel.info.JvmChecker.checkJvmCompatibilityAndIssueWarning(JvmChecker.java:72)
neo4jMaven    | 	at org.neo4j.graphdb.factory.module.GlobalModule.<init>(GlobalModule.java:203)
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.createGlobalModule(DatabaseManagementServiceFactory.java:272)
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:133)
neo4jMaven    | 	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142)
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95)
neo4jMaven    | 	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:34)
neo4jMaven    | Caused by: java.io.IOException: No space left on device
neo4jMaven    | 	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
neo4jMaven    | 	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:250)
neo4jMaven    | 	... 33 more
neo4jMaven    | ERROR StatusLogger An exception occurred processing Appender neo4jLog.debug.log
neo4jMaven    |  org.neo4j.logging.shaded.log4j.core.appender.AppenderLoggingException: Error writing to stream /logs/debug.log
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:252)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.FileManager.writeToDestination(FileManager.java:277)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.rolling.RollingFileManager.writeToDestination(RollingFileManager.java:275)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:294)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:312)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.config.DefaultReliabilityStrategy.log(DefaultReliabilityStrategy.java:63)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.Logger.log(Logger.java:161)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2661)
neo4jMaven    | 	at org.neo4j.logging.log4j.Log4jLog.warn(Log4jLog.java:124)
neo4jMaven    | 	at org.neo4j.kernel.info.JvmChecker.checkJvmCompatibilityAndIssueWarning(JvmChecker.java:72)
neo4jMaven    | 	at org.neo4j.graphdb.factory.module.GlobalModule.<init>(GlobalModule.java:203)
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.createGlobalModule(DatabaseManagementServiceFactory.java:272)
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:133)
neo4jMaven    | 	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142)
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95)
neo4jMaven    | 	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:34)
neo4jMaven    | Caused by: java.io.IOException: No space left on device
neo4jMaven    | 	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
neo4jMaven    | 	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
neo4jMaven    | 	at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:250)
neo4jMaven    | 	... 33 more
neo4jMaven    | 2024-10-10 09:04:43.453+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474.
neo4jMaven    | java.lang.RuntimeException: java.io.IOException: No space left on device
neo4jMaven    | 	at org.neo4j.dbms.identity.AbstractIdentityModule.readOrGenerate(AbstractIdentityModule.java:69) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.dbms.identity.DefaultIdentityModule.<init>(DefaultIdentityModule.java:46) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.dbms.identity.DefaultIdentityModule.fromGlobalModule(DefaultIdentityModule.java:39) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.graphdb.factory.module.edition.CommunityEditionModule.<init>(CommunityEditionModule.java:146) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:134) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142) [neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95) [neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:34) [neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | Caused by: java.io.IOException: No space left on device
neo4jMaven    | 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
neo4jMaven    | 	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
neo4jMaven    | 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
neo4jMaven    | 	at sun.nio.ch.IOUtil.write(IOUtil.java:79) ~[?:?]
neo4jMaven    | 	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280) ~[?:?]
neo4jMaven    | 	at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
neo4jMaven    | 	at java.nio.channels.Channels.writeFully(Channels.java:97) ~[?:?]
neo4jMaven    | 	at java.nio.channels.Channels$1.write(Channels.java:172) ~[?:?]
neo4jMaven    | 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
neo4jMaven    | 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
neo4jMaven    | 	at java.io.FilterOutputStream.close(FilterOutputStream.java:182) ~[?:?]
neo4jMaven    | 	at java.io.FilterOutputStream.close(FilterOutputStream.java:191) ~[?:?]
neo4jMaven    | 	at org.neo4j.io.fs.OutputStreamWritableChannel.close(OutputStreamWritableChannel.java:101) ~[neo4j-io-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.io.state.SimpleFileStorage.writeState(SimpleFileStorage.java:79) ~[neo4j-io-4.4.36.jar:4.4.36]
neo4jMaven    | 	at org.neo4j.dbms.identity.AbstractIdentityModule.readOrGenerate(AbstractIdentityModule.java:62) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 	... 8 more
neo4jMaven    | 	Suppressed: java.io.IOException: No space left on device
neo4jMaven    | 		at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
neo4jMaven    | 		at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]
neo4jMaven    | 		at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
neo4jMaven    | 		at sun.nio.ch.IOUtil.write(IOUtil.java:79) ~[?:?]
neo4jMaven    | 		at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280) ~[?:?]
neo4jMaven    | 		at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
neo4jMaven    | 		at java.nio.channels.Channels.writeFully(Channels.java:97) ~[?:?]
neo4jMaven    | 		at java.nio.channels.Channels$1.write(Channels.java:172) ~[?:?]
neo4jMaven    | 		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
neo4jMaven    | 		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
neo4jMaven    | 		at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[?:?]
neo4jMaven    | 		at java.io.FilterOutputStream.close(FilterOutputStream.java:182) ~[?:?]
neo4jMaven    | 		at org.neo4j.io.fs.OutputStreamWritableChannel.close(OutputStreamWritableChannel.java:101) ~[neo4j-io-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.io.state.SimpleFileStorage.writeState(SimpleFileStorage.java:79) ~[neo4j-io-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.dbms.identity.AbstractIdentityModule.readOrGenerate(AbstractIdentityModule.java:62) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.dbms.identity.DefaultIdentityModule.<init>(DefaultIdentityModule.java:46) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.dbms.identity.DefaultIdentityModule.fromGlobalModule(DefaultIdentityModule.java:39) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.graphdb.factory.module.edition.CommunityEditionModule.<init>(CommunityEditionModule.java:146) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:134) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36) ~[neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142) [neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95) [neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 		at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:34) [neo4j-4.4.36.jar:4.4.36]
neo4jMaven    | 2024-10-10 09:04:43.456+0000 INFO  Neo4j Server shutdown initiated by request
neo4jMaven    | 2024-10-10 09:04:43.457+0000 INFO  Stopped.
neo4jMaven exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container neo4jMaven exited (1)
```

**Comment by pascalpoizat** [comment]
Hello

solution seems to be to increase the virtual disk limit.

Docker Desktop -> Parameters -> Resources -> Advanced : set virtual disk limit to 120 GB.

**Comment by pascalpoizat** [comment]
Now I get issue #2 so I close this one and continue there.
